name: Release workflow
on: [pull_request, push]

jobs:
  core-cicd-job:
    name: Core CI/CD
    runs-on: ubuntu-latest
    steps:
      - name: Checkout core
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Prepare dot-cicd
        run: |
          chmod +x .cicd/discover.sh
          .cicd/discover.sh
      - name: Build DotCMS Image
        run: |
          dotcicd/library/pipeline/github/core/buildBase.sh
        env:
          PROJECT_ID: cicd-246518
          LICENSE_KEY: ${{ secrets.DOTCMS_LICENSE }}
      - name: Build Integration Tests Image
        run: |
          dotcicd/library/pipeline/github/core/buildIntegration.sh
        env:
          PROJECT_ID: cicd-246518
          LICENSE_KEY: ${{ secrets.DOTCMS_LICENSE }}
      - name: Build Curl Tests Image
        run: |
          dotcicd/library/pipeline/github/core/buildCurl.sh
        env:
          PROJECT_ID: cicd-246518
      - name: Run Unit Tests
        run: |
          dotcicd/library/pipeline/github/core/runUnit.sh
        env:
          PROJECT_ID: cicd-246518
          EXPORT_REPORTS: true
#      - name: Run Curl Tests
#        run: |
#          dotcicd/library/pipeline/github/core/runCurl.sh
#        env:
#          PROJECT_ID: cicd-246518
#          LICENSE_KEY: ${{ secrets.DOTCMS_LICENSE }}
#          IMAGE_BASE_NAME: gcr.io/cicd-246518/curl-tests-image:${{ github.run_number }}
#          EXPORT_REPORTS: true
#          DB_TYPE: postgres
#          PROVIDER_DB_USERNAME: postgres
#          PROVIDER_DB_PASSWORD: postgres


