name: Run Dockerized Tests
on: [pull_request]

jobs:
  run-unit-integration-tests-job:
    name: Core Tests
    runs-on: ubuntu-latest
    env:
      DOT_CICD_CLOUD_PROVIDER: github
      DOT_CICD_TARGET: core
      PROJECT_ID: cicd-246518
      EXPORT_REPORTS: true
      GITHUB_USER: dotcmsbuild
      GITHUB_USER_TOKEN: ${{ secrets.USER_TOKEN }}
      PULL_REQUEST: ${{ github.event.number }}
    steps:
      - name: Checkout core
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: GITHUB CONTEXT
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Set Common Vars
        run: |
          echo ::set-env name=CURRENT_BRANCH::$(
            if [[ -z "${{ github.event.number }}" ]]; then
              echo $(basename "${{ github.ref }}")
            else
              echo "${{ github.head_ref }}"
            fi)
          echo "OJO:>> ${CURRENT_BRANCH}"
          echo ::set-env name=commitMsg::$(git log --format=%B -n 1 ${{ github.event.after }})
      - name: Prepare dot-cicd
        run: |
          chmod +x .cicd/discover.sh && .cicd/discover.sh
      - name: Build Tests Base Image
        run: |
          source dotcicd/library/pipeline.sh buildTestsBase
        env:
          LICENSE_KEY: ${{ secrets.DOTCMS_LICENSE }}
      - name: Run Unit Tests
        run: |
          source dotcicd/library/pipeline.sh runUnit
#      - name: Run Integration Tests - postgres
#        run: |
#          source dotcicd/library/pipeline.sh runIntegration
#        env:
#          databaseType: postgres
#        if: (!startsWith(env.commitMsg, '[github mysql]') && !startsWith(env.commitMsg, '[github oracle]') && !startsWith(env.commitMsg, '[github mssql]')) || startsWith(env.commitMsg, '[github]') || startsWith(env.commitMsg, '[github postgres]')
#      - name: Run Integration Tests - mysql
#        run: |
#          source dotcicd/library/pipeline.sh runIntegration
#        env:
#          databaseType: mysql
#        if: (github.head_ref == 'master' || startsWith(github.head_ref, 'release-') || startsWith(github.head_ref, 'test-'))
#  run-curl-tests-job:
#    name: Core Curl (Postman) Tests
#    runs-on: ubuntu-latest
#    env:
#      DOT_CICD_CLOUD_PROVIDER: github
#      DOT_CICD_TARGET: core
#      PROJECT_ID: cicd-246518
#      EXPORT_REPORTS: true
#      GITHUB_USER: dotcmsbuild
#      GITHUB_USER_TOKEN: ${{ secrets.USER_TOKEN }}
#      PULL_REQUEST: ${{ github.event.number }}
#    steps:
#      - name: Checkout core
#        uses: actions/checkout@v2
#        with:
#          fetch-depth: 1
#      - name: Prepare dot-cicd
#        run: |
#          chmod +x .cicd/discover.sh && .cicd/discover.sh
#      - name: Build DotCMS Image
#        run: |
#          dotcicd/library/pipeline.sh buildBase
#        env:
#          PROJECT_ID: cicd-246518
#          LICENSE_KEY: ${{ secrets.DOTCMS_LICENSE }}
#      - name: Build Tests Base Image
#        run: |
#          source dotcicd/library/pipeline.sh buildTestsBase
#        env:
#          LICENSE_KEY: ${{ secrets.DOTCMS_LICENSE }}
#      - name: Run Curl Tests
#        run: |
#          dotcicd/library/pipeline.sh runCurl
#        env:
#          PROJECT_ID: cicd-246518
#          LICENSE_KEY: ${{ secrets.DOTCMS_LICENSE }}
#          databaseType: postgres
#          PROVIDER_DB_USERNAME: postgres
#          PROVIDER_DB_PASSWORD: postgres
