name: Run Dockerized Tests
on: [pull_request, push]

jobs:
  core-cicd-tests-job:
    name: Core CI/CD
    runs-on: ubuntu-latest
    env:
      DOT_CICD_CLOUD_PROVIDER: github
      DOT_CICD_TARGET: core
      PROJECT_ID: cicd-246518
      EXPORT_REPORTS: true
    steps:
      - name: Checkout core
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Prepare dot-cicd
        run: |
          chmod +x .cicd/discover.sh && .cicd/discover.sh
#      - name: Build DotCMS Image
#        run: |
#          dotcicd/library/pipeline.sh buildBase
#        env:
#          PROJECT_ID: cicd-246518
#          LICENSE_KEY: ${{ secrets.DOTCMS_LICENSE }}
      - name: Build Base Tests Image
        run: |
          source dotcicd/library/pipeline.sh buildBaseTests
        env:
          LICENSE_KEY: ${{ secrets.DOTCMS_LICENSE }}
      - name: Run Unit Tests
        run: |
          source dotcicd/library/pipeline.sh runUnit
        if: succeeded() || failed()
      - name: Run Integration Tests
        run: |
          source dotcicd/library/pipeline.sh runIntegration
        env:
          databaseType: postgres
        if: succeeded() || failed()

#      - name: Run Curl Tests
#        run: |
#          dotcicd/library/pipeline.sh runCurl
#        env:
#          PROJECT_ID: cicd-246518
#          LICENSE_KEY: ${{ secrets.DOTCMS_LICENSE }}
#          IMAGE_BASE_NAME: gcr.io/cicd-246518/curl-tests-image:${{ github.run_number }}
#          EXPORT_REPORTS: true
#          DB_TYPE: postgres
#          PROVIDER_DB_USERNAME: postgres
#          PROVIDER_DB_PASSWORD: postgres


