name: Release workflow
on: [pull_request, push]

jobs:
  core-cicd-job:
    name: Core CI/CD
    runs-on: ubuntu-latest
    steps:
      - name: Checkout core
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Prepare dot-cicd
        run: |
          chmod +x .cicd/discover.sh
          .cicd/discover.sh
      - name: Build DotCMS Image
        run: |
          dotcicd/library/pipeline/github/core/buildBase.sh ${{ secrets.DOTCMS_LICENSE }}
        env:
          PROJECT_ID: cicd-246518
      - name: Build Integration Tests Image
        run: |
          dotcicd/library/pipeline/github/core/buildIntegration.sh ${{ secrets.DOTCMS_LICENSE }}
        env:
          PROJECT_ID: cicd-246518
      - name: Build Curl Tests Image
        run: |
          dotcicd/library/pipeline/github/core/buildCurl.sh
        env:
          PROJECT_ID: cicd-246518
#      - name: Curl Tests Compose
#        run: |
#          docker-compose \
#            -f ./docker/tests/curl/travis-curl-service.yml \
#            -f ./docker/tests/shared/sidecar-service-compose.yml \
#            -f ./docker/tests/shared/$DB_TYPE-docker-compose.yml \
#            -f ./docker/tests/shared/open-distro-docker-compose.yml \
#            up \
#            --abort-on-container-exit
#        env:
#          PROJECT_ID: cicd-246518
#          IMAGE_BASE_NAME: gcr.io/cicd-246518/curl-tests-image:${{ github.run_number }}
#          DB_TYPE: postgres
#          EXPORT_REPORTS: true
#          PROVIDER_DB_USERNAME: postgres
#          PROVIDER_DB_PASSWORD: postgres
#          BUILD_ID: ${{ github.ref }}
#          BUILD_HASH: ${{ github.sha }}

